val greater = 3 > 2;
val less = 1 < 2;
val equal = 8 = 8;
val realGreater = 2.0 > 1.0;
val realLess = 1.0 < 2.0;
val integerGreaterOrEqual = 3 >= 3;
val integerLessOrEqual = 3 <= 3;
val integerNotEqual = 3 <> 4;
val realGreaterOrEqual = 2.0 >= 2.0;
val realLessOrEqual = 2.0 <= 2.0;
val yes = 1 < 2;
val no = 3 < 2;
val booleanNotEqual = yes <> no;
val trueLiteral = true;
val falseLiteral = false;
val trueBranch = if true then 10 else 20;
val falseBranch = if false then 10 else 20;
val comparisonBranch = if 2 >= 2 then 30 else 40;
val nestedBranch = if true then if false then 50 else 60 else 70;
val booleanBranch = if false then true else false;
val realBranch = if 1 < 2 then 1.5 else 2.5;
