#!/usr/bin/env python3
"""Import an external SML test suite into tests/fixtures, sorted by Poly/ML.

Poly/ML is the only oracle. Each upstream program lands in one of:

    tests/fixtures/<suite>/                Poly/ML and Nassau agree
    tests/fixtures/<suite>/error/          Poly/ML and Nassau both reject
    tests/fixtures/<suite>.unsupported/    Poly/ML accepts, Nassau does not match
    tests/fixtures/<suite>.unsupported/error/
                                           Poly/ML rejects, Nassau accepts
    tests/fixtures/<suite>.ignored/        Poly/ML itself does not behave as the
                                           suite expects (reason on line 2)

Programs that cannot run on any Poly/ML-checked harness (MLton.* primitives,
FFI imports, `use`) are skipped and listed with a reason in
tests/fixtures/<suite>/EXCLUDED.tsv. Re-running with the pinned commit
reproduces the same layout. The FileCheck blocks are then generated by
tools/update_filecheck.py.

Usage:
    tools/import_suite.py mlton --source /path/to/mlton-checkout
    tools/import_suite.py mlton --source DIR --dry-run
"""

import argparse
import re
import shutil
import subprocess
import sys
import tempfile
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

import update_filecheck as uf

ROOT = uf.ROOT
FIXTURES = ROOT / "tests" / "fixtures"
TIMEOUT = 30

SUITES = {
    "mlton": {
        "repo": "https://github.com/MLton/mlton.git",
        "commit": "5fe943391e539a502699327a6266b6e8e97939e1",
        "license": "LICENSE",
        "license_name": "HPND",
        "sparse": ["regression"],
        "valid": ("regression", "*.sml"),
        "reject": ("regression/fail", "*.sml"),
    },
}

EXCLUSIONS = [
    (re.compile(r"\bMLton\s*\."), "uses MLton.* primitives"),
    (re.compile(r"\b_(?:import|export|address|symbol|prim|overload)\b"), "uses MLton FFI or primitive syntax"),
    (re.compile(r"^\s*use\s+\""), "loads other files with use"),
    (re.compile(r"\$\((?:SML_LIB|\w+)\)"), "refers to a basis path variable"),
]


def exclusion(source):
    for pattern, reason in EXCLUSIONS:
        if pattern.search(source):
            return reason
    return None


def run_limited(command, cwd):
    try:
        return subprocess.run(command, cwd=cwd, input=b"", capture_output=True, timeout=TIMEOUT)
    except subprocess.TimeoutExpired:
        return None


def poly_result(oracle, path):
    """(accepted, stdout, stderr, code, reason); None when Poly/ML times out."""
    try:
        first = oracle.polyml_program(path)
        second = oracle.polyml_program(path)
    except subprocess.TimeoutExpired:
        return None
    return first, second


def nassau_rejects(oracle, path):
    result = run_limited([oracle.nassau, str(path)], path.parent)
    if result is None:
        return False
    path.with_suffix("").unlink(missing_ok=True)
    return result.returncode != 0 and "×" in uf.ANSI.sub("", uf.decode(result.stderr))


def nassau_matches(oracle, path, stdout, code):
    compiled = run_limited([oracle.nassau, str(path)], path.parent)
    executable = path.with_suffix("")
    try:
        if compiled is None or compiled.returncode != 0:
            return False
        native = run_limited([str(executable)], path.parent)
    finally:
        executable.unlink(missing_ok=True)
    interpreted = run_limited([oracle.nassau, "--interpret", str(path)], path.parent)
    if native is None or interpreted is None:
        return False
    return all(
        uf.decode(run.stdout) == stdout and run.returncode == code and not run.stderr
        for run in (native, interpreted)
    )


def classify_valid(oracle, path):
    timed = poly_result(oracle, path)
    if timed is None:
        return "ignored", "Poly/ML timed out"
    (stdout, stderr, code), (again, _, _) = timed
    if "error: " in stderr:
        return "ignored", "Poly/ML rejects this program"
    if code != 0:
        return "ignored", f"Poly/ML exits with status {code}"
    if stdout != again:
        return "ignored", "output differs between Poly/ML runs"
    if nassau_matches(oracle, path, stdout, code):
        return "pass", None
    return "unsupported", None


def classify_reject(oracle, path):
    timed = poly_result(oracle, path)
    if timed is None:
        return "ignored/error", "Poly/ML timed out"
    (_, stderr, code), _ = timed
    if "error: " not in stderr:
        return "ignored/error", "Poly/ML accepts this program, which the suite expects to be rejected"
    if nassau_rejects(oracle, path):
        return "error", None
    return "unsupported/error", None


def header(suite, config, relative, ignored_reason):
    lines = [
        f"(* {suite} {relative} @{config['commit'][:9]}; "
        f"{config['license_name']} licence in tests/fixtures/{suite}/LICENSE *)"
    ]
    if ignored_reason:
        lines.append(f"(* IGNORED: {ignored_reason} *)")
    return ("\n".join(lines) + "\n").encode()


def checkout(config, source):
    if not source.exists():
        subprocess.run(
            ["git", "clone", "--quiet", "--filter=blob:none", "--no-checkout", config["repo"], str(source)],
            check=True,
        )
        subprocess.run(["git", "-C", str(source), "sparse-checkout", "set", *config["sparse"]], check=True)
        subprocess.run(["git", "-C", str(source), "checkout", "--quiet", config["commit"]], check=True)
    head = subprocess.run(
        ["git", "-C", str(source), "rev-parse", "HEAD"], capture_output=True, text=True, check=True
    ).stdout.strip()
    if head != config["commit"]:
        raise uf.ToolError(f"{source} is at {head}, expected pinned commit {config['commit']}")


def destination(suite, bucket, name):
    directories = {
        "pass": FIXTURES / suite,
        "error": FIXTURES / suite / "error",
        "unsupported": FIXTURES / f"{suite}.unsupported",
        "unsupported/error": FIXTURES / f"{suite}.unsupported" / "error",
        "ignored": FIXTURES / f"{suite}.ignored",
        "ignored/error": FIXTURES / f"{suite}.ignored" / "error",
    }
    return directories[bucket] / name


BUCKETS = {
    "valid": ["pass", "unsupported", "ignored"],
    "reject": ["error", "unsupported/error", "ignored/error"],
}


def main():
    parser = argparse.ArgumentParser(description=(__doc__ or "").split("\n\n")[0])
    parser.add_argument("suite", choices=sorted(SUITES))
    parser.add_argument("--source", required=True, type=Path, help="checkout of the upstream repo (cloned if missing)")
    parser.add_argument("--nassau", default=str(ROOT / "target" / "release" / "nassau"))
    parser.add_argument("--polyml", default="poly")
    parser.add_argument("--dry-run", action="store_true", help="print bucket counts only")
    parser.add_argument("--jobs", type=int, default=8)
    args = parser.parse_args()

    if shutil.which(args.polyml) is None:
        raise uf.ToolError(f"Poly/ML not found ({args.polyml})")
    config = SUITES[args.suite]
    checkout(config, args.source)
    oracle = uf.Oracle(args.polyml, args.nassau)

    work = []
    for kind in ("valid", "reject"):
        directory, pattern = config[kind]
        for path in sorted((args.source / directory).glob(pattern)):
            work.append((kind, path, path.relative_to(args.source).as_posix()))

    def sort(item):
        kind, path, relative = item
        data = path.read_bytes()
        reason = exclusion(data.decode("latin-1"))
        if reason:
            return item, data, "excluded", reason
        with tempfile.TemporaryDirectory() as directory:
            staged = Path(directory) / path.name
            staged.write_bytes(header(args.suite, config, relative, None) + data)
            classify = classify_valid if kind == "valid" else classify_reject
            bucket, why = classify(oracle, staged)
        return item, data, bucket, why

    with ThreadPoolExecutor(args.jobs) as pool:
        results = list(pool.map(sort, work))

    counts = {}
    for _, _, bucket, _ in results:
        counts[bucket] = counts.get(bucket, 0) + 1
    for bucket, count in sorted(counts.items()):
        print(f"{bucket}: {count}")
    if args.dry_run:
        return

    suite_dir = FIXTURES / args.suite
    suite_dir.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(args.source / config["license"], suite_dir / "LICENSE")
    (suite_dir / "PROVENANCE").write_text(
        f"repository: {config['repo']}\ncommit: {config['commit']}\n"
        f"licence: {config['license_name']} (LICENSE)\n"
        "imported with tools/import_suite.py; the only local edit is the header comment\n"
    )
    excluded = []
    for (kind, path, relative), data, bucket, why in results:
        for other in BUCKETS[kind]:
            destination(args.suite, other, path.name).unlink(missing_ok=True)
        if bucket == "excluded":
            excluded.append(f"{relative}\t{why}")
            continue
        target = destination(args.suite, bucket, path.name)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(header(args.suite, config, relative, why if bucket.startswith("ignored") else None) + data)
    (suite_dir / "EXCLUDED.tsv").write_text("\n".join(sorted(excluded)) + "\n")

    patterns = [f"tests/fixtures/{args.suite}/**/*.sml", f"tests/fixtures/{args.suite}.unsupported/**/*.sml"]
    subprocess.run(
        [sys.executable, str(ROOT / "tools" / "update_filecheck.py"), "--no-build", "--nassau", args.nassau, *patterns],
        check=False,
    )


if __name__ == "__main__":
    try:
        main()
    except uf.ToolError as error:
        print(f"error: {error}", file=sys.stderr)
        sys.exit(1)
